### ISSUE TITLE
Translation key for 'new' should be global

### ISSUE THREAD

**Issue by itschn** [HitFox/foxinator-generator#13]
https://github.com/HitFox/foxinator-generator/blob/a8ea640f74d1fbceb6cf0931098172bf5841ceb8/lib/generators/foxinator/setup/templates/cms/app/views/admin/base/_collection_actions.html.haml

``` ruby
t('.new', resource_name: resource_class.model_name.human)
```

should be:

``` ruby
t('new', resource_name: resource_class.model_name.human)
```

so only one key is needed. 
The according translation then will be on toplevel and should look like:

``` ruby
en:
    new: 'new %{resource_name}'
```

**Comment by declarus** [comment]
Fix is merged and closed.
