### ISSUE TITLE
Foxinator create command creates wrong template for right column

### ISSUE THREAD

**Issue by DominicBreuker** [HitFox/foxinator-generator#16]
There is one partial in the base folder that is called "_right_column.html.haml". It contains code valid for all views in the admin interface and additionally renders a "_right_column_after.html.haml", which accommodates custom code for different models. Currently, each call of the foxinator create method generates a right_column, not a right_column_after. This should be changed.

Additionally, the "_right_column_after.html.haml" partial depends on a helper called "collection?", which is currently not generated by the foxinator setup command.

**Comment by declarus** [comment]
Fixed!
