### ISSUE TITLE
Roles - Controller

### ISSUE THREAD

**Issue by DominicBreuker** [HitFox/foxinator-generator#21]
Add flash messages in roles controller:

def sync_and_permit
   Permission.sync_and_permit_admins!
   redirect_to [current_namespace, resource_class], notice: t('flash.success', action_name: t('.sync_and_permit'))
 end

 def sync
   Permission.sync
   redirect_to [current_namespace, resource_class], notice: t('flash.success', action_name: t('.sync'))
 end

**Comment by declarus** [comment]
fixed
