### ISSUE TITLE
Why does Foxinator not depend on Comfy?

### ISSUE THREAD

**Issue by janv** [HitFox/foxinator-generator#3]
This is more of a question than an issue.
- If Comfy is essential to the Foxinator gem, it should be a dependency.
- If Comfy is _not_ essential to the Foxinator gem, it should be completely separate.

Could you explain what the relationship here is?

If there's a dependency between the two, shouldn't our gems be versioned/tagged?

**Comment by declarus** [comment]
It's because Comfy is a github fork and as far as I know, you cannot add a dependency when it points to a git repository.

**Comment by declarus** [comment]
Closed because we now depend on the Comfortable Mexican Loveseat, an extension of the CMS.
