### ISSUE TITLE
Adding two state machine Gems

### ISSUE THREAD

**Issue by klaustopher** [HitFox/foxinator-generator#32]
This gem uses `state_machine` (version 1.2.0) and `state_machines-activerecord` (version 0.2.0) explicitly. `state_machines-activerecord` has a dependency on the `state_machines` (version 0.2.0). (Note, one is machine**s**, the other is just machine)

So, using the current version of the foxinator generator adds two StateMachine gems, that both use the same syntax for state machines.

We do some checks if a given class includes a state machine and when using hte current version of foxinator generator, it is not clear which of the following is correct:

``` ruby
resource.class.include?(StateMachine::InstanceMethods)

resource.class.include?(StateMachines::InstanceMethods)
```

I do not really want to check for both ;) So, would it be possible to settle for either `state_machine` or `state_machines`?

//cc @declarus

**Comment by declarus** [comment]
@itschn Thoughts on this?

**Comment by declarus** [comment]
Hey @klaustopher, I've set up a PR for this issue. I'll wait to merge it in until @itschn gets back from vacation to do a code review.
