### ISSUE TITLE
Manual steps during foxinator:setup

### ISSUE THREAD

**Issue by janv** [HitFox/foxinator-generator#4]
When you run `rails g foxinator:setup`, you're prompted on screen to perform some manual steps by the devise generator:
- Ensure you have defined default url options in your environments files
- Ensure you have defined root_url
- Ensure you have flash messages in app layout

If any of these are actually necessary, can we have our setup perform them?

A lot of migrations are generated by the different steps of the `foxinator:setup` and I'm asked to run them manually. Can't we run the migrations automatically at the end of `foxinator:setup`?

**Comment by declarus** [comment]
First part of your question: those are standard devise notifications, and handling them should be on a per-project basis.

Second part: I think it's possible, would need to look into it though.

**Comment by declarus** [comment]
rake db:migrate and the admins:setup task now happen automatically.
