### ISSUE TITLE
Seed data for foxinator

### ISSUE THREAD

**Issue by janv** [HitFox/foxinator-generator#5]
After going through all the steps of `foxinator:setup` and running the migrations manually, opening the rails app just gives an error.  I would expect  the setup to
- Generate a site skeleton
- Generate an admin use

@DemitryT I was thinking if it makes sense to expect foxinator to "work out of the box" or if "works out of the box" is only a requirement for the suspenders.

**Comment by declarus** [comment]
The foxinator gem only installs the CMS admin interface and some other goodies, so it does work out of the box. If you go to localhost:3000/en/admin/login, and assuming you've run the rake admins:setup command, you can log in and start creating a site. It's not designed to provide an out of the box consumer-facing website

**Comment by itschn** [comment]
1+ for the site skeleton
