### ISSUE TITLE
Move state machine to https://github.com/state-machines/state_machines

### ISSUE THREAD

**Issue by itschn** [HitFox/foxinator-generator#8]
this gem is maintained, in oposite to https://github.com/pluginaweek/state_machine

**Comment by declarus** [comment]
@itschn After our work on Collecto, I'm configuring the foxinator-generator to be like Collecto (with the state_machines-activerecord, '~>0.2.0' gem)

See https://github.com/HitFox/foxinator-generator/issues/11
